### ISSUE TITLE
.vue or .ascx files with nested template tags fail to compile

### ISSUE THREAD

**Issue by AdrianBathurst** [mbdavid/DotVue#2]
.vue or .ascx file with components that have nested template tags fail to compile correctly. Content after the next template tag gets stripped.
```
<template>
    some content...
    <a-component>
        <template ...params...>
            some content... (content after here is stripped)
        </template>
        <template ...params...>
            some content...
        </template>
    </a-component>
    some content...
</template>
```

**Comment by mbdavid** [comment]
Thanks @AdrianBathurst, it's a regex problem. I will fix it

**Comment by mbdavid** [comment]
Hi @AdrianBathurst, I was checking here and I already fix this. Are you using lastest version? Take a look on LayoutContent.ascx example, it's use inner templates.

**Comment by AdrianBathurst** [comment]
Updating to latest version fixed it...thank you! I must remember to check for updates first! :)
