### ISSUE TITLE
Control what data is in the request/response

### ISSUE THREAD

**Issue by AdrianBathurst** [mbdavid/DotVue#3]
Currently every request will contain data from all the client side data properties and the response will contain data from all the server side public properties. When dealing with large data sets, this becomes a big overhead with large quantities of data being sent/received with every request, even if you decide to make a small change to some property.

Is there any way around this? Would be nice to be able to control what data is added to the request/response.

**Comment by AdrianBathurst** [comment]
Kind of related additional issue... some "unmodified" data is being added back to the response.

The `JToken.DeepEquals` that checks for property changes is not working correctly.

I load an array in my vue component, make no changes to it, then do a post back. See this line here checking for a difference: ` if (!JToken.DeepEquals(original[item.Key], item.Value))`. Here, `JToken.DeepEquals` returns false.

I compared the `original[item.Key]` and `item.Value`  values myself...they are identical, yet DeepEquals returns false and adds my "unmodified" array back into the response.

**Comment by mbdavid** [comment]
Your array is from a primitive type or custom class (can you paste this class here?).

**Comment by AdrianBathurst** [comment]
My test array...

```
public class Agenda : ViewModel
{
	public Data data = new Data();
	public string SomeTitle = "some title";

	public Agenda()
	{
	}

	[Ready]
	protected override void OnCreated()
	{
		data.Days = new List<Day>();
			
		data.DateFormat = "";
		data.TimeFormat = "";

		List<TimeSlot> TimeSlots = new List<TimeSlot>
		{
			new TimeSlot() { Time = new Time(){ Start="10:00", End="11:00" }, Title = "slot #1", Live = true },
			new TimeSlot() { Time = new Time(){ Start="11:00", End="" }, Title = "slot #2", Live = true },
			new TimeSlot() { Time = new Time(){ Start="12:00", End="00:00" }, Title = "slot #3", Live = true }
		};

		data.Days.Add(new Day() { Date = "2017-07-19T00:00:00", TimeSlots = TimeSlots });

		TimeSlots = new List<TimeSlot>
		{
			new TimeSlot() { Time = new Time(){ Start="10:30", End="11:30" }, Title = "slot #4", Live = true },
			new TimeSlot() { Time = new Time(){ Start="11:30", End="12:30" }, Title = "slot #5", Live = true },
			new TimeSlot() { Time = new Time(){ Start="12:30", End="13:30" }, Title = "slot #6", Live = true }
		};

		data.Days.Add(new Day() { Date = "2017-07-20T00:00:00", TimeSlots = TimeSlots });
	}

	public void Save(string newTitle)
	{
		SomeTitle = newTitle;
	}
}

public struct Data
{
	public List<Day> Days { get; set; }
	public string DateFormat { get; set; }
	public string TimeFormat { get; set; }
}

public struct Day
{
	public string Date { get; set; }
	public List<TimeSlot> TimeSlots { get; set; }
}

public struct TimeSlot
{
	public Time Time { get; set; }
	public string Title { get; set; }
	public bool Live { get; set; }
}

public struct Time
{
	public string Start { get; set; }
	public string End { get; set; }
}
```

**Comment by mbdavid** [comment]
Hi @AdrianBathurst, after some research this "bug" occurs in DeepEquals that doen't works as I excepted. I found this implementation: https://stackoverflow.com/questions/33022993/compare-two-arbitrary-jtoken-s-of-the-same-structure
In your example is now working...

Thanks for using!

BTW, DotVue still in early stage and some changes can breake existing API. I will use DotVue in my next big project soon, so i'm still fixing and adding some features that I will need. I will add in nuget only when

**Comment by AdrianBathurst** [comment]
Thank you! That's fixed it.

Re my original issue that I mentioned... using large data sets adds large overhead to each request as all the data is posted. It would be nice to be able to control what data is sent/received.

Maybe have a post object to add the properties of the data you want posted and have a response object to add the properties of the data you want returned?

Then there would be no need to have to look for changes that DeepEquals was doing as you are in control of what's returned.

**Comment by mbdavid** [comment]
In my first version I created a attribute to mark any property that will be only "Server to Client". In this case, this object will never sent from client to server (and of course, can't be used in server). It's ideal for large resultsets when client will not change.

I can add back this to make some tests

**Comment by mbdavid** [comment]
Done. Now you can use `[Local]` attribute to not send from client to server. Must be not initialized (set as `null`) on ctor `ViewModel` class.

**Comment by AdrianBathurst** [comment]
Thank you for doing this!

Back to the agenda example, my "data" property is not being added to "local"....
"Data" was a struct before, is now a class.


![2017-07-24_150344](https://user-images.githubusercontent.com/9006517/28527152-9b973c4c-7081-11e7-8fd0-d6eaff3ed269.png)


agenda file...

```
<%@ Control Language="C#" %>
<script runat="server">

	public class Agenda : ViewModel
	{
		[Local]
		public Data data;
		public string SomeTitle = "some title";
		[Local]
		public List<string> Items { get; set; }

		public Agenda()
		{
		}

		[Ready]
		protected override void OnCreated()
		{
			Items = new List<string> { "a", "b", "c" };

			data = new Data();
			data.Days = new List<Day>();

			data.DateFormat = "";
			data.TimeFormat = "";

			List<TimeSlot> TimeSlots = new List<TimeSlot>
			{
				new TimeSlot() { Time = new Time(){ Start="10:00", End="11:00" }, Title = "slot #1", Live = true },
				new TimeSlot() { Time = new Time(){ Start="11:00", End="" }, Title = "slot #2", Live = true },
				new TimeSlot() { Time = new Time(){ Start="12:00", End="00:00" }, Title = "slot #3", Live = true }
			};

			data.Days.Add(new Day() { Date = "2017-07-19T00:00:00", TimeSlots = TimeSlots });

			TimeSlots = new List<TimeSlot>
			{
				new TimeSlot() { Time = new Time(){ Start="10:30", End="11:30" }, Title = "slot #4", Live = true },
				new TimeSlot() { Time = new Time(){ Start="11:30", End="12:30" }, Title = "slot #5", Live = true },
				new TimeSlot() { Time = new Time(){ Start="12:30", End="13:30" }, Title = "slot #6", Live = true }
			};

			data.Days.Add(new Day() { Date = "2017-07-20T00:00:00", TimeSlots = TimeSlots });
		}

		public void Save(string newTitle)
		{
			SomeTitle = newTitle;
		}
	}

	public class Data
	{
		public List<Day> Days { get; set; }
		public string DateFormat { get; set; }
		public string TimeFormat { get; set; }
	}

	public struct Day
	{
		public string Date { get; set; }
		public List<TimeSlot> TimeSlots { get; set; }
	}

	public struct TimeSlot
	{
		public Time Time { get; set; }
		public string Title { get; set; }
		public bool Live { get; set; }
	}

	public struct Time
	{
		public string Start { get; set; }
		public string End { get; set; }
	}

</script>
<template>
    <div>
        <button @click="Save('new text')">Send to Server :: {{ SomeTitle }}</button>
        <pre>$data: {{ $data }}</pre>
        <pre>$props: {{ $props }}</pre>
    </div>
</template>
```

**Comment by mbdavid** [comment]
humm... thats because I'm getting only for properties:

```
            foreach(var l in type
                .GetProperties(BindingFlags.Instance | BindingFlags.Public)
                .Where(x => x.GetCustomAttribute<LocalAttribute>() != null)
                .Select(x => x.Name))
            {
                this.Locals.Add(l);
            }
```

**Comment by AdrianBathurst** [comment]
To get round that, I use a "property" instead by adding my class definition to a dictionary...

```
[Local]
public Dictionary<string, Data> myData { get; set; }
```

then inside OnCreated...

```
myData = new Dictionary<string, Data>();
Data Data = new Data();
do stuff...
myData.Add("data", Data);
```

That all works fine, I get correct "local" data. But in template...

```
<div v-for="day in myData.data.Days">
```

`v-for` throws error `Cannot read property 'data' of null`.

As `myData` cannot be initialized server side and therefore cannot return a good initial property definition, `myData.data` is not defined on first render...

```
data: function() {
    return {"SomeTitle":"some title","myData":null,"Items":null};
  },
```

If we could have `[Local]` properties initialized server side, then `data` would be defined initially like this, and it would work...

```
data: function() {
    return {"SomeTitle":"some title","myData":{data:{}},"Items":null};
  },
```

So using `[Local]` is a nice idea, but it has the issue of not rendering required initial data property definitions.

**Comment by mbdavid** [comment]
Hi @AdrianBathurst, I was thiniking (and I didnt test yet) but I beleave that works with non null data, but initializing you property on ctor (or in definition on c# 6) , like

```
[Local]
public Dictionary<string, Data> myData { get; set; } = new Dictionary<string, Data>() { ["data"] = null };
```

This will produce data like: 

```
data: function() {
    return {"SomeTitle":"some title","myData":{data:{}},"Items":null};
  },
```

And you can still use `OnCreated` method to populate your dictionary with external data source. It's important not populate in ctor because constructor are called in every "postback".

**Comment by AdrianBathurst** [comment]
Getting closer!

I'm using c# 5. I tried...

```
[Local]
public Dictionary<string, Data> myData { get; set; }

public Agenda()
{
	myData = new Dictionary<string, Data>() { ["data"] = new Data() };
}
```

in OnCreated...

```
Data Data = new Data();
do stuff...
myData["data"] = Data;
```

Then...

![2017-07-25_140014](https://user-images.githubusercontent.com/9006517/28573550-ea96c2b0-7142-11e7-9cae-6811150bf302.jpg)


![2017-07-25_140509](https://user-images.githubusercontent.com/9006517/28573556-ee07b30a-7142-11e7-914e-0dfc225bc8f8.jpg)


![2017-07-25_140740](https://user-images.githubusercontent.com/9006517/28573563-f0fb75b0-7142-11e7-84a3-1ccaf337ed3e.jpg)

**Comment by mbdavid** [comment]
yeah, if is initialized in ctor this value are lost when cheking diffs. I fixed in this commit. Try again

**Comment by AdrianBathurst** [comment]
Working nicely now. Thank you!!!
