### ISSUE TITLE
.ascx files to use code behind .cs files

### ISSUE THREAD

**Issue by AdrianBathurst** [mbdavid/DotVue#5]
Would it be possible to use code-behind .cs files for the server-side code that's in the ascx files? I tried but failed to get it to work.

so `<%@ Control Language="C#" %>` becomes `<%@ Control Language="C#" AutoEventWireup="false" CodeBehind="SomeModule.ascx.cs" Inherits="MyNamespace.UI.SomeModule" %>`

**Comment by AdrianBathurst** [comment]
I see your recent update uses code-behind with .vue files....perfect! Thank you! Looking forward to using your recent version, it's looking very good. Thanks again for sharing this project, it's brilliant!

**Comment by mbdavid** [comment]
Hi @AdrianBathurst, 1 year later :)

I convert this lib to NET Core (net standard) and ascx do not exists there. This new version are much better and I'm really using in a mobile app. Also, it's on nuget now.

Enjoy!
